# Data Science coding exercises
## Sathyanarayan Rao


### Q1. Given two arrays, write a python code to compute the intersection of the two arrays. 

In [1]:
import numpy as np
X = [1,5,9,0]; Y = [3,0,2,9];
Z = np.intersect1d(X,Y);

In [2]:
Z

array([0, 9])

#### Suppose if list contains strings and non-numeric data also, numpy intersect works fine

Here we will add strings in the list and demonstrate

In [3]:
X1 = [1,'a','b',4,6]; Y1 = [3,4,'a',9]
Z1 = np.intersect1d(X1,Y1);

In [4]:
Z1

array(['4', 'a'], dtype='<U11')

### Q2. Create a Matrix in numpy and invert it

In [5]:
matrix = np.matrix('1 2 2; 1 2 7; 3 2 1');
matrix

matrix([[1, 2, 2],
        [1, 2, 7],
        [3, 2, 1]])

#### First check if matrix is singular

A singular matrix is a square matrix if its determinant is 0.  


In [6]:
np.linalg.det(matrix)

20.000000000000007

In [7]:
inverted_matrix = np.linalg.inv(matrix)
inverted_matrix

matrix([[-0.6 ,  0.1 ,  0.5 ],
        [ 1.  , -0.25, -0.25],
        [-0.2 ,  0.2 , -0.  ]])

In [8]:
matrix2 = np.matrix('1 2 2;1 2 2;3 2 1');
matrix2

matrix([[1, 2, 2],
        [1, 2, 2],
        [3, 2, 1]])

In [9]:
np.linalg.det(matrix2)

0.0

if determinant is zero, inversion in numpy should give us singular matrix warning.

In [10]:
np.linalg.inv(matrix2)

LinAlgError: Singular matrix

### Q3. Illustrate that lists are mutable and tuples not. 

In [11]:
# create a tuple
A = ('sa','ri','ga','ma','pa','dha','ni');
# create a list
B = ['sa','ri','ga','ma','pa','dha','ni'];

In [12]:
A

('sa', 'ri', 'ga', 'ma', 'pa', 'dha', 'ni')

In [13]:
B

['sa', 'ri', 'ga', 'ma', 'pa', 'dha', 'ni']

In [14]:
# trying to overwrite a tuple which is not mutable
A[0] = '0'

TypeError: 'tuple' object does not support item assignment

In [15]:
# trying to overwrite a list which is mutable
B[0]='0'

In [16]:
B

['0', 'ri', 'ga', 'ma', 'pa', 'dha', 'ni']

### Q4. Find largest number along values in a dictionary

In [17]:
# define a dictionary

dictionary = {'a': 10, 'b': 20, 'c': 33,'d': 12, 'e': 17, 'f': 19}
# create an empty list
temp = [];
for i in dictionary.values():
    temp.append(i);
print(max(temp))

33


### Q5. Use lambda inline function to compute eucleadean distance between two points

In [18]:
eucleadean = lambda x1,y1,x2,y2: np.sqrt((x2-x1)**2+(y2-y1)**2)

In [19]:
eucleadean(0,4,6,2)

6.324555320336759

### Q6. Illustrate the functionality of a enumerate function

In [20]:
# using enumerate object to print values of a list
swaras = ['sa', 'ri', 'ga', 'ma', 'pa', 'dha', 'ni'];
enum = enumerate(swaras);
for swara in enum:
    print(swara)


(0, 'sa')
(1, 'ri')
(2, 'ga')
(3, 'ma')
(4, 'pa')
(5, 'dha')
(6, 'ni')


In [21]:
# getting rid of brackets
swaras = ['sa', 'ri', 'ga', 'ma', 'pa', 'dha', 'ni'];
enum = enumerate(swaras);
for count,swara in enum:
    print(count,swara)

0 sa
1 ri
2 ga
3 ma
4 pa
5 dha
6 ni


### Q7. print todays and yesterdays date using datetime module

In [22]:
from datetime import datetime, timedelta
today = datetime.now()
print("Today is: "+ today.strftime('%d-%m-%Y'))
yesterday = today - timedelta(hours = 24)
print("Yesterday was: "+ yesterday.strftime('%d-%m-%Y'))


Today is: 20-05-2022
Yesterday was: 19-05-2022


In [23]:
a_list = [10, 38, 73, 82]
for i, j in enumerate(a_list):
	print(i, j)

0 10
1 38
2 73
3 82


### Q8. create a numeric pandas series and extract every even entries

In [24]:
import pandas as pd
series = pd.Series([1,8,3,2,4,5,6,2,1,5,56,7,7,7,1,3,4])
series

0      1
1      8
2      3
3      2
4      4
5      5
6      6
7      2
8      1
9      5
10    56
11     7
12     7
13     7
14     1
15     3
16     4
dtype: int64

In [25]:
even_index = []
for i in range(len(series)):
    if(i%2==0):
        even_index.append(i);

even_series = series.take(even_index);
even_series

0      1
2      3
4      4
6      6
8      1
10    56
12     7
14     1
16     4
dtype: int64

### Q9. illustrate map function 

- map function is a in-built python function that iterates over a iterable and applies transformation to each iterable.
- syntax: output = map(function, iterable);

In [26]:
def x10(num):
    return num*10

X = [1,2,3,4,5];
Y = list(map(x10,X));
Y

[10, 20, 30, 40, 50]

In [27]:
Y1 = list(map(lambda x:x*10,X));
Y1

[10, 20, 30, 40, 50]

### Q10. change string list to uppercase using map function

In [29]:
string_list = ['ball','cat','a','b','c'];

In [38]:
capitalized = list(map(lambda x:x.upper(),string_list));
capitalized

['BALL', 'CAT', 'A', 'B', 'C']